### ISSUE TITLE
I status menus

### ISSUE THREAD

**Issue by Knvgpt** [bjango/istatd#1]
## The format has a bug.

whatever I set it to, it gives me the opposite of that in the menu bar. it only displays the correct format of Mb/s or MB/s under the processes and not the menu bar. I couldn't find a contact us or an email. or repo named I status menus.. this was the closest name. so I thought this might be the one. 

cheers,
Kanav

**Comment by marcedwards** [comment]
Hi! This may be due to an issue with a feature we have. If you hold option when the network menu is open, it switches between Mb and MB (it will temporarily show the opposite to your settings).

It can get stuck if you open the menu, press option, then close the menu before releasing the option key. We’re looking to fix this, but for now, opening the menu and pressing then releasing option should get it working again. Please let me know if that helps!

**Comment by Knvgpt** [comment]
yes thanks a lot @marcedwards  that worked..
